#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: pndb-model-nearr27-deployment
spec:
  selector:
    matchLabels:
      app: pndb-model-nearr27-server
  replicas: 1
  template:
    metadata:
      labels:
        app: pndb-model-nearr27-server
    spec:
      containers:
      - name: pndb-model-nearr27-container
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/rustcohle27/fastapipndb22:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: pndb-model-nearr27-service
  name: pndb-model-nearr27-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: pndb-model-nearr27-server
  type: LoadBalancer
