#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapipnd-deployment
spec:
  selector:
    matchLabels:
      app: fastapipnd-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapipnd-server
    spec:
      containers:
      - name: fastapipnd
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/rustcohle27/fastpndbapi:latest
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: fastapipnd-service
  name: fastapipnd-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fastapipnd-server
  type: LoadBalancer