#manifest
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fastapipnd22-deployment
spec:
  selector:
    matchLabels:
      app: fastapipnd22-server
  replicas: 1
  template:
    metadata:
      labels:
        app: fastapipnd22-server
    spec:
      containers:
      - name: fastapipnd22
        #image: gcr.io/tensorflow-serving/resnet 
        image: docker.io/rustcohle27/fastapipndb22:{github.sha}
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  labels:
    run: fastapipnd22-service
  name: fastapipnd22-service
spec:
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: fastapipnd22-server
  type: LoadBalancer